# Generated by Django 5.1.4 on 2025-01-03 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_event_event_location_event_event_animal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_id',
            field=models.AutoField(default=67, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_animal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_animal_type', to='animal.type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.staff'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='animal_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_nin',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_animal', to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.staff'),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='task_log_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.staff'),
        ),
        migrations.AlterField(
            model_name='task_log',
            name='task_log_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal.task'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
